{{- if .Values.cognito.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ template "superset.fullname" . }}-cognito
  namespace: {{ include "base.namespace" . }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.cognito.secretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ template "superset.fullname" . }}-cognito-env
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.cognito.secretArn }}
{{- end }}
