version: 0.2

env:
  variables:
    CLUSTER_NAME: "sb-dev-cluster"
    region: "us-east-1"

phases:
  install:
    runtime-versions: {}
    commands:
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install --update
      - aws --version

      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - sudo mv kubectl /usr/local/bin/
      - kubectl version --client

      - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - helm version

      - sudo wget -qO /usr/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
      - sudo chmod +x /usr/bin/yq
      - yq --version

  pre_build:
    commands:
      - cd helmcharts/kitchen
      - chmod +x install.sh
      - echo "Checking AWS identity..."
      - aws sts get-caller-identity
      - echo "Listing EKS clusters..."
      - aws eks list-clusters --region $AWS_DEFAULT_REGION
      - echo "Describing cluster..."
      - aws eks describe-cluster --region $AWS_DEFAULT_REGION --name $CLUSTER_NAME
      - aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name $CLUSTER_NAME
      - kubectl get nodes

  build:
    on-failure: ABORT
    commands:
      - export cloud_env=aws
      - time ./install.sh core-setup

  post_build:
    commands:

      - echo "Deployment completed successfully."

